services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:v1.7.1

    container_name: ${ANVIL_CONTAINER_NAME}

    entrypoint:
      - anvil

    command:
      - --host
      - 0.0.0.0
      - --port
      - ${ANVIL_PORT}
      - --chain-id
      - ${ANVIL_CHAIN_ID}
      - --accounts
      - ${ANVIL_ACCOUNTS}
      - --balance
      - ${ANVIL_BALANCE}
      - --mnemonic
      - ${ANVIL_MNEMONIC}

      # 自动加载/保存区块链状态
      - --state
      - /var/data/anvil_state.json

      # 每 10 秒自动保存一次
      - --state-interval
      - "10"

    ports:
      - "${ANVIL_PORT}:8545"

    volumes:
      - ./anvil-data:/var/data

    healthcheck:
      test:
        [
          "CMD",
          "cast",
          "block-number",
          "--rpc-url",
          "http://127.0.0.1:8545"
        ]
      interval: 2s
      timeout: 3s
      retries: 10

  deployer:
    image: ${IMAGE:-ghcr.io/nettedx/nettedx-blockchain:latest}

    container_name: ${DEPLOYER_CONTAINER_NAME}

    depends_on:
      anvil:
        condition: service_healthy

    environment:
      RPC_URL: ${RPC_URL}
      PRIVATE_KEY: ${PRIVATE_KEY}

    entrypoint:
      - forge
    
    command:
      - script
      - script/Deploy.s.sol
      - --rpc-url
      - ${RPC_URL}
      - --broadcast

    volumes:
      - ./broadcast:/app/broadcast
      - ./address-data:/app/address-data